### ISSUE TITLE
SAT beam widths

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4sim#12]
It looks like the SAT beams are different between `s4sim` and the table in the DSR.

https://github.com/CMB-S4/s4sim/blob/a8d3a5e3056a33985679cd19f18da61cdf557005/s4sim/hardware/config.py#L884-L892

![](https://user-images.githubusercontent.com/383090/80241991-7268da00-8619-11ea-8ae8-709c8d3ba24a.png)

Do you know what is going on?

**Comment by smsimon** [comment]
The SAT optics are the same for a given telescope, so the beam should be frequency dependent. I assumed that the beam sizes being the same size between frequency bands in each telescope was a typo. I got the beam sizes for the higher frequencies in the band pairs from the spreadsheet linked in the instrument DSR spreadsheet.

**Comment by zonca** [comment]
thanks @smsimon, it seems reasonable to me,
@cbischoff what do you think?

**Comment by cbischoff** [comment]
The SAT design assumes that the cold stop is strongly under-illuminated, following the BICEP design. If we look at the 85/145 dichroic pixels for example, at 85 GHz the beam is larger out of the horn/antenna but this leads to larger aperture illumination, so the net effect is that the far field beam size is mostly frequency-independent. I don't think the Table 3-1 numbers come from any full-blown physical optics calculation, but they are based on some calculations and I don't think they are a typo.

**Comment by smsimon** [comment]
I guess I am a bit confused then since in the spreadsheet, even the scaled SO designs have the same FWHM between the two frequency bands (which is not the case for SO), and the monochromatic BICEP scaled designs show frequency dependence. I will check with the instrument folks to get some more details on these calculations.

https://docs.google.com/spreadsheets/d/1B9A5-IYr1wAbOUgFDcnYv7q0_WXgXNU7EhlfBRqavm4/edit#gid=329331219

**Comment by cbischoff** [comment]
Thanks for linking that spreadsheet!

For monochromatic options 1-4, there is different pixel pitch at each frequency presumably chosen to keep the stop illumination constant at each frequency, in which case you would get the usual beamwidth ~ 1/nu relationship for fixed aperture size.

I'm not sure about the details of the SO-derived designs.

**Comment by cbischoff** [comment]
But for the purposes of these sims, isn't the goal to follow the DSR design? So shouldn't we just stick with what in those tables, even if it might change in the future?

**Comment by smsimon** [comment]
The pixel size changing makes much more sense. I agree that we should do the DSR design--I just want to get final sign-off and double check.

**Comment by smsimon** [comment]
Made a pull request with this update
