### ISSUE TITLE
Sampling frequency

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4sim#14]
I am looking through https://github.com/CMB-S4/s4sim/blob/master/s4sim/hardware/config.py but I cannot find the sampling frequency of the channels.
I need that to crosscheck that my scaling of the hitmaps makes sense.
Can you please help me out?

**Comment by jdborrill** [comment]
400Hz LAT, 100Hz SAT

J

**Comment by keskitalo** [comment]
The simulation ran at 200Hz LAT, 20Hz SAT. The exact sampling rate does not matter, just as long as the hit maps come out uniformly sampled.
