### ISSUE TITLE
Use "C" in Chilean band names and "P" in South Pole band names

### ISSUE THREAD

**Issue by keskitalo** [CMB-S4/s4sim#18]
The NET calculation is site-specific and LAT bands in the Pole now have "P" included in the name to make them distinct from Chile.

The Chilean bands should similarly have "C" in their name and the SAT bands should follow the same naming convention. This would make it more intuitive and easier to use in scripting.

This issue also addresses the absence of Chile-specific SAT bands.

**Comment by smsimon** [comment]
Implemented new naming conventions in DC1 pull request
