### ISSUE TITLE
Band of middle-frequency channels

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4sim#6]
@keskitalo @smsimon 

my first assumption was that MFH meant middle-frequency-high, instead looking at `s4sim`
it looks like the `1` channels are low and the `2` channels are high:

```
import s4sim.hardware.config
c=s4sim.hardware.config.get_example()
for ch in ["MFHS1", "MFHS2", "MFLS1", "MFLS2"]:
    print(ch, c.data["bands"][ch]["center"])
MFHS1 95.0
MFHS2 155.1
MFLS1 85.0
MFLS2 145.1
```

can you please confirm `s4sim` is correct as it is now?

**Comment by smsimon** [comment]
MFH is the higher of the two MF bands in the SAT. 1 and 2 indicate whether the band is 90 or 150 GHz. This is consistent with the other bands.

**Comment by zonca** [comment]
ok thanks!
