### ISSUE TITLE
NET for LAT

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4sim#7]
In https://github.com/CMB-S4/s4sim/blob/master/s4sim/hardware/config_3shooter.py

I think the LAT NET figures are by mistake the same as the SAT ones.

For example at https://github.com/CMB-S4/s4sim/blob/cff68286815593054bdb6866ad7aa115f1bf89b7/s4sim/hardware/config_3shooter.py#L306

the LFL1 NET is 177, but that is the SAT value, from the DSR:

![Screenshot 2020-04-24 at 00 33 28](https://user-images.githubusercontent.com/383090/80241985-7137ad00-8619-11ea-9866-986134b9cf39.png)
![Screenshot 2020-04-24 at 00 33 05](https://user-images.githubusercontent.com/383090/80241991-7268da00-8619-11ea-8ae8-709c8d3ba24a.png)

**Comment by smsimon** [comment]
There are two different estimations for noise in the LAT. One using scaled noise and one using the SO sensitivity calculator. These are both included here: https://docs.google.com/spreadsheets/d/17KtDIc7pHTdL2F_22RZHve7l0vf-IY_YwMDVXQoEdnE/edit#gid=0. Looks like the scaled one (which is what was input initially) now has a note that it needs to be updated, so it may be beneficial to use the SO sensitivity calculation values instead.

**Comment by smsimon** [comment]
I am checking with the instrument group to see which version they prefer us to use since the numbers in their spreadsheet also don't match the numbers in the DSR.

**Comment by zonca** [comment]
@keskitalo did you use what is in `s4sim` for the design sim tool simulations?

**Comment by keskitalo** [comment]
@zonca I did. All noise levels come directly from `s4sim`.

**Comment by smsimon** [comment]
Just put in a pull request for the updated LAT noise values.

**Comment by zonca** [comment]
see https://github.com/CMB-S4/s4sim/pull/8

**Comment by jdborrill** [comment]
I'm confused that the numbers in the DSR (Table 3.2) are neither of the
sets of numbers in the reference design spreadsheet (rows 17 & 18).

Julian

**Comment by smsimon** [comment]
They are close for all but UHF, I think. According to Ruhl there were some ad-hoc corrections trying to account for different numbers of detectors but there was confusion about which was better. I took the more conservative value between the two.

**Comment by jdborrill** [comment]
Frequency 20 27 39 93 145 225 278
CDT 214 177 224 238 320 747 1281
SO_V3 325 387 247 305 385 854 2077
DSR 438 383 250 302 356 737 1840

Julian

**Comment by keskitalo** [comment]
Julian's table with fixed width formatting
```
          Frequency  
source     20   27   39   93  145  225   278
--------------------------------------------
CDT       214  177  224  238  320  747  1281
SO_V3     325  387  247  305  385  854  2077
DSR       438  383  250  302  356  737  1840
```

**Comment by smsimon** [comment]
SO v3 is what the LAT will be using going forward on the instrument side, and their releases will offer good traceability. We at least know what went into those numbers for these sensitivity numbers. It seems like there isn't a lot of info on what happened to get the DSR numbers but they were tweaked from the SO v3 numbers. The CDT numbers appear to be from very different pixel sizes, so it makes sense that those would be very different.
